# Generated by Django 3.1.12 on 2021-06-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(default='입금대기', max_length=100),
        ),
    ]
