# Generated by Django 3.1.12 on 2021-07-01 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservation', '0002_auto_20210630_2158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.TextField(choices=[('입금대기', '입금대기'), ('입금완료', '입금완료')], default='입금대기', max_length=100),
        ),
    ]
